apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: worker
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: worker
    spec:
      containers:
      - image: engineerball/worker:a7d3c12f9ed668f5b8f734a2b85910209fc8f60d
        imagePullPolicy: IfNotPresent
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
