apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: voting
    track: stable 
  name: voting
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: voting
      track: stable 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: voting
        track: stable
    spec:
      containers:
      - image: engineerball/example-voting-voting:null.14
        imagePullPolicy: IfNotPresent
        name: voting
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
