apiVersion: v1
kind: Service
metadata:
  labels:
    run: voting
  name: voting
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: voting
  sessionAffinity: None
  type: LoadBalancer
#  type: NodePort
